### ISSUE TITLE
Where is "ResNet-101-model.npz" ?

### ISSUE THREAD

**Issue by angleboy8** [machanic/AU_R-CNN#2]
I tested your demo, but I didn't find the ResNet-101-model.npz. I hope you can provide this model. Thank you!

**Comment by sharpstill** [comment]
The ResNet-101-model.npz is loading the ImageNet pretrained file at the first training. It is converted from caffenet. You can check this page and source code to see how to download and convert.
https://docs.chainer.org/en/stable/reference/generated/chainer.links.ResNet101Layers.html#chainer.links.ResNet101Layers
Also I will upload the npz file into Google Drive so that you can directly download.

**Comment by angleboy8** [comment]
I appreciate your help. I hope you will upload your google cloud earlier.

**Comment by sharpstill** [comment]
@angleboy8 I have uploaded all the training necessary files onto [https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN](https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN)

**Comment by rswethashankar92** [comment]
while testing the demo, i think i need to change the weight_params in HeatMapGenerator class, please help me

**Comment by machanic** [comment]
@rswethashankar92 Which .py file do you use? Can you describe more detail?

**Comment by machanic** [comment]
@angleboy8 All the pretrained model file(.npz) are located here : https://cloud.tsinghua.edu.cn/d/8190d64e83ef43b7ab3f/?p=%2FBP4D_dataset_trained_model&mode=list
